### PR TITLE
Web Client: Display task params & various fixes

### LINKED ISSUE #523: task creation form: small details
for `web-client` -> `TaskCreationForm.vue`

- `List of labels` seems to appear twice?
- `threshold`: i think this has been removed from [TrainingInformation](https://github.com/epfml/disco/blob/develop/discojs/discojs-core/src/task/training_information.ts)
- let's add a title on top of the page for clarity. maybe also very brief intro text on what will happen here

### LINKED ISSUE #527: web-client: when joining a task in the 'task description' tab, show all training_info parameters of the task
showing all params in the task definition (`TrainingInformation`)would be most useful, as the decisions to join a task might depend on some of them. we can maybe show it if once clicks on a info/details button.

such as for example the privacy parameters etc. 

can reuse maybe the list from the task creation form?

thanks hadrien for reporting

### PR DESCRIPTION
**Pull request by s314cy**
## Features (Web Client)

- Task Creation Form
  - Added a textual introduction to the page
  - Removed stale fields
  - Added a "Privacy Parameters" section
- Task Description
  - Display all defined task parameters
  - For the sake of transparency, privacy parameters are explicitly displayed as "Unused" if they are undefined
 
## Linked issues

Fixes #523 and #527

### CODE REVIEW

File: web-client/src/task_creation_form.ts [hunk 1]
```diff
@@ -421,6 +391,73 @@ export const modelCompileData: FormSection = {
   ]
 }
 
+export const privacyParameters: FormSection = {
+  id: 'privacyParameters',
+  title: 'Privacy Parameters',
+  fields: [
+    {
+      id: 'noiseScale',
+      name: 'Noise Scale',
```
Comment (martinjaggi) [inline web-client/src/task_creation_form.ts:403]: DP Noise Scale

File: web-client/src/task_creation_form.ts [hunk 2]
```diff
@@ -421,6 +391,73 @@ export const modelCompileData: FormSection = {
...
+      yup: yup.number().positive(),
+      as: 'input',
+      type: 'number'
+    },
+    {
+      id: 'clippingRadius',
+      name: 'Clipping Radius',
```
Comment (martinjaggi) [inline web-client/src/task_creation_form.ts]: DP Clipping Radius

File: web-client/src/task_creation_form.ts [hunk 3]
```diff
@@ -421,6 +391,73 @@ export const modelCompileData: FormSection = {
...
+      yup: yup.boolean().required(),
+      as: 'input',
+      type: 'checkbox',
+      dependencies: {
+        scheme: 'Federated'
+      }
+    },
+    {
+      id: 'tauPercentile',
+      name: 'Tau Percentile',
```
Comment (martinjaggi) [inline web-client/src/task_creation_form.ts:450]: desc: Percentile of Trusted Users for Byzantine Robust Aggregation

**Review by martinjaggi — APPROVED** [review]
