### PR TITLE
Fix and rework GPT-TF.js

### LINKED ISSUE #654: Improve and rework GPT-tfjs
Here is a list of potential improvements for gpt-tfjs in Disco:
- [x] Create a compile method to initialize the optimizer (rather than initializing it when fitDataset is called). This ensures the optimizer state is persisted across multiple calls to fitDataset
- [x] Implement save and load methods to save and re-use a trained model
- [x] Rename classes for better clarity and consistency, e.g. multiple classes and functions are called `GPT`
- [x] Assess whether we can use tf.CustomCallbackArgs rather than redefining an interface for TrainingCallbacks
- [x] Assess whenever we can use TFJS' native fitDataset method rather than overriding it with a custom training loop
-> tfjs only implements Adam while GPT2 uses AdamW. Additionally, the custom optimizer allows having weight decay which is used in the original GPT2.
- [x] Reading a text file with TF.js only supports reading line by line which is not ideal for LLM inputs, try implementing a file reader chunk by chunk rather than by lines 
- [x] Training with gpt2 has NaN loss after the first epoch step 

#656 and #657 should be addressed first

### PR DESCRIPTION
**Pull request by JulienVig**
Closes #654 

* Fix weight initialization from zero to random uniform -> Fixes GPT2 NaN loss
* Implement weight sharing between token embeddings and the language modeling head -> -20% memory footprint
* Improve generation with top k sampling option
* Add seed for deterministic runs
* Implement text loaders by byte chunk rather than by line which doesn't require to pad each line to the context length
* Waiting on Transformers.js [#984](https://github.com/huggingface/transformers.js/issues/984) and [#1019](https://github.com/huggingface/transformers.js/issues/1019#issuecomment-2465803843) to migrate to @huggingface/transformers v3.

### CODE REVIEW

File: discojs-node/src/loaders/text.ts [hunk 1]
```diff
@@ -1,14 +1,98 @@
...
+          tokens.slice(currentPosition),
+          { skip_special_tokens: true }
+        )
+        debug("End of chunk, remaining text: '%s'", endOfPreviousChunk)
+      } else {
+        // Note that the difference between tokenizing and then concatenating
+        // vs concatenating and then tokenizing can happen if their is no
+        // remaining text. We consider this difference negligible
+        endOfPreviousChunk = "";
+      }
```
Comment (tharvik) [inline discojs-node/src/loaders/text.ts]: duplicated in discojs-web/loaders/text. that hints to me that it shouldn't happen in the loader but applied after.
the issue at hand is that lines where outputted by the previous version. I think we can change it to output characters (single letter `string`) instead. that also would drop the `blockSize`, `batchSize` & `minChunkSize` argument which aren't really relevant for reading text ([separation of concerns](https://en.wikipedia.org/wiki/Separation_of_concerns) and all that)

in the newly merged processing PR (#781), it is much simpler to combine such transformation, I think that smth like
```ts
loadText($path).batch($blockSize).map((block) => tokenize(block, $tokenizer))
```
with tokenize updated to accept block/`List<string>` instead, and maybe drop the padding (but what would be the behavior at the end of the file?)

File: discojs-node/src/loaders/text.ts [hunk 2]
```diff
@@ -1,14 +1,98 @@
...
+ * big enough to contain at least one batch.
+ * @param minChunkSize default to 16KiB, the minimum size of each chunk in bits
+ * @returns a dataset of tokenized input and label sequences
+ */
+export function load(path: string, tokenizer: PreTrainedTokenizer,
+  blockSize: number, batchSize: number = 1, minChunkSize = 16384): Dataset<Text> {
   return new Dataset(async function* () {
-    const input = (await fs.open(path)).createReadStream({ encoding: "utf8" });
+    if (batchSize < 1 || blockSize < 1 || minChunkSize < 1)
+      throw new Error("batchSize, blockSize and minChunkSize must be positive integers");
```
Comment (tharvik) [inline discojs-node/src/loaders/text.ts]: positive checked but not that it is integral.

```suggestion
    if (batchSize < 1 || !Number.isInteger(batchSize) || blockSize < 1 || !Number.isInteger(blockSize) || minChunkSize < 1 || !Number.isInteger(minChunkSize))
      throw new Error("batchSize, blockSize and minChunkSize must be positive integers");
```

File: discojs-node/src/loaders/text.ts [hunk 3]
```diff
@@ -1,14 +1,98 @@
...
+const debug = createDebug("discojs-node:loaders:text");
+
+/**
+ * Returns a Dataset that streams and tokenizes text to yield tokenized sequences
+ * one at a time. Each sequence has size `blockSize` + 1, where the first `blockSize`
+ * tokens are the input and the last token is the label. The following sequence
+ * starts with the last token of the previous sequence (so the previous label is now the 
+ * first input token).
+ * In other words, the dataset yields sequences of size `blockSize` + 1 but with an overlap
+ * of 1 token between each sequence.
```
Comment (tharvik) [inline discojs-node/src/loaders/text.ts]: why is the overlap needed? I mean, it looks like a more complicated feature than a needed one. I guess that you wanted to use the dataset "in full" and not let the label of a given block only in the output.
based on the understanding I got from [the video you sent me a while back](https://www.youtube.com/watch?v=kCc8FmEb1nY&t=1020), if we want to actually use each token fairly, we need to "slide over" the token stream (such as [`slice.windows` in glorious Rust](https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.windows)) (it still treat unfairly the end of the file but that should be fixed by padding if really wanted).
edit: that also helps with avoiding the "+ 1" everywhere.

File: cli/src/benchmark_gpt.ts [hunk 4]
```diff
@@ -79,43 +79,24 @@ async function main(args: Required<CLIArguments>): Promise<void> {
       maxIter: iterationsPerEpoch,
       blockSize: contextLength,
       lr: 0.0001,
-      vocabSize: 50258 // default wikitext task uses the gpt2 tokenizer with vocabSize 50258
+      vocabSize: 50257 // default wikitext task uses the gpt2 tokenizer with vocabSize 50257
```
Comment (tharvik) [inline cli/src/benchmark_gpt.ts]: can we have it as a default in `GPTConfig`? I saw it a few times and that's quite a magic value and I didn't found a way to extract it from the tokenizer either.

File: discojs-node/src/loaders.spec.ts [hunk 5]
```diff
@@ -50,13 +52,83 @@ describe("image directory parser", () => {
...
+      expect(await parsed.size()).to.equal(1);
+      const next = await parsed[Symbol.asyncIterator]().next()
+      expect(next.done).to.be.false;
+      
+      const tokens = next.value as number[]
+      const expectedTokens = models.tokenize(tokenizer, text, {
+        padding: false,
+        truncation: false,
+        return_tensor: false
+      })
```
Comment (tharvik) [inline discojs-node/src/loaders.spec.ts]: yeah, better to test for the actual tokens values. it is not really an issue but it assumes that `models.tokenize` will always work as expected. also, I built test codebases with a bunch of logic testing like this and while it looks correct, it breaks quite easily.

File: discojs-node/src/loaders.spec.ts [hunk 6]
```diff
@@ -50,13 +52,83 @@ describe("image directory parser", () => {
...
-      await fs.writeFile(path, ["a", "b", "c"].join("\n"));
+      const text = ["a", "b", "c"].join("\n")
+      await fs.writeFile(path, text);
+      // set block size to 4 to get 1 sequence of 4 tokens + 1 label token
+      const parsed = loadText(path, tokenizer, 4, 1);
+      expect(await parsed.size()).to.equal(1);
+      const next = await parsed[Symbol.asyncIterator]().next()
+      expect(next.done).to.be.false;
+      
+      const tokens = next.value as number[]
```
Comment (tharvik) [inline discojs-node/src/loaders.spec.ts]: better to check for the whole dataset content, with `Array.fromAsync` (as locally redone in discojs/src/dataset/dataset.spec.ts), that's more readable and ensure that it doesn't generate more values that expected

File: discojs-node/src/loaders.spec.ts [hunk 7]
```diff
@@ -50,13 +52,83 @@ describe("image directory parser", () => {
 });
 
 describe("text parser", () => {
+  
   it("parses basic file", async () => {
+    const tokenizer = await AutoTokenizer.from_pretrained('Xenova/gpt2')
```
Comment (tharvik) [inline discojs-node/src/loaders.spec.ts]: we also test with "Xenova/gpt2", but our code should work with any tokenizer; can you switch it to another one?

File: discojs-node/src/loaders.spec.ts [hunk 8]
```diff
@@ -50,13 +52,83 @@ describe("image directory parser", () => {
...
+      const blockSize = 4
+      const parsed = loadText(path, tokenizer, blockSize, 1);
+      // expect the number of sequences to be the total number of tokens divided by blockSize
+      // we use floor because the last incomplete sequence is dropped
+      expect(await parsed.size()).to.equal(Math.floor(expectedTokens.length / blockSize));
+      
+      let i = 0
+      for await (const tokens of parsed) {
+        // each sequence should have length blockSize + 1 (for the label)
+        expect(tokens).to.deep.equal(expectedTokens.slice(i, i + blockSize + 1));
```
Comment (tharvik) [inline discojs-node/src/loaders.spec.ts]: this tests more that advertisez, you can simplify it by only checking for the size of each block.

File: discojs-node/src/loaders.spec.ts [hunk 9]
```diff
@@ -50,13 +52,83 @@ describe("image directory parser", () => {
...
+        // but the window should move by blockSize only
+        i += blockSize
+      }
+    })
+  });
+
+  it("reads multiple chunks", async () => {
+    const tokenizer = await AutoTokenizer.from_pretrained('Xenova/gpt2')
+    await withFile(async ({ path }) => {
+      const text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed risus maximus, ultricies ex sed, dictum elit. Curabitur faucibus egestas enim et auctor. Quisque vel dignissim turpis. Curabitur justo tellus, elementum sit amet erat eget, auctor ornare nisi. Nunc tortor odio, ultrices id leo vitae, euismod congue ex. Curabitur arcu leo, sagittis quis felis nec, imperdiet aliquet tellus. Integer a mollis nulla. Quisque pulvinar lectus eget nisi pharetra, non molestie magna ullamcorper. Sed porttitor diam non blandit molestie. Duis tristique arcu ut efficitur efficitur. Fusce et ullamcorper tortor. Pellentesque a accumsan lacus, nec mollis risus. Nunc quis eros a orci ultricies cursus. Maecenas sodales ipsum a magna malesuada efficitur. Maecenas at sapien blandit, egestas nisi eu, mollis elit."
```
Comment (tharvik) [inline discojs-node/src/loaders.spec.ts]: please split it into multiple lines using `[…].join(" ")`, that's more readable.

File: discojs-node/src/loaders.spec.ts [hunk 10]
```diff
@@ -50,13 +52,83 @@ describe("image directory parser", () => {
...
+        expect(tokens).to.deep.equal(expectedTokens.slice(i, i + blockSize + 1));
+        // but the window should move by blockSize only
+        i += blockSize
+      }
+    })
+  });
+
+  it("reads multiple chunks", async () => {
+    const tokenizer = await AutoTokenizer.from_pretrained('Xenova/gpt2')
+    await withFile(async ({ path }) => {
```
Comment (tharvik) [inline discojs-node/src/loaders.spec.ts]: consider moving the definitions and the actions not neede the file outside of `withFile` (also for the previous ones). you can actually return a value out of `withFile` if wanted.

File: discojs-node/src/loaders.spec.ts [hunk 11]
```diff
@@ -50,13 +52,83 @@ describe("image directory parser", () => {
...
+      // we use floor because the last incomplete sequence is dropped
+      expect(await parsed.size()).to.equal(Math.floor(expectedTokens.length / blockSize));
+    
+      let i = 0
+      for await (const tokens of parsed) {
+        // each sequence should have length blockSize + 1 (for the label)
+        expect(tokens).to.deep.equal(expectedTokens.slice(i, i + blockSize + 1));
+        // but the window should move by blockSize only
+        i += blockSize
+      }
```
Comment (tharvik) [inline discojs-node/src/loaders.spec.ts]: duplicated from previous test. consider a common function.

File: discojs-node/src/loaders/text.ts [hunk 12]
```diff
@@ -1,14 +1,98 @@
...
+ * 
+ * @param path path to the text file to read
+ * @param tokenizer the tokenizer to use, should match the model that will be trained
+ * @param blockSize the context length, the maximum number of tokens of input sequences
+ * @param batchSize default to 1, the number of input sequences (of `blockSize` tokens) in each batch.
```
Comment (tharvik) [inline discojs-node/src/loaders/text.ts]: seems to be kinda duplicated from blockSize

File: discojs-web/src/loaders.spec.ts [hunk 13]
```diff
@@ -22,22 +24,51 @@ describe("csv parser", () => {
...
+
     // jsdom doesn't implement .text on File/Blob
     // trick from https://github.com/jsdom/jsdom/issues/2555
-    const text = await (
-      await fetch(
-        // data URL content need to be url-encoded
-        ["data:,first", "second", "third"].join("%0A"),
-      )
+    const file = await (
+      await fetch( "data:," + encodeURIComponent(text))
```
Comment (tharvik) [inline discojs-web/src/loaders.spec.ts:30]: hooo nice, well found!

File: discojs-web/src/loaders.spec.ts
Comment (tharvik) [inline discojs-web/src/loaders.spec.ts:1]: similar remarks as the one in discojs-node

File: discojs-web/src/loaders/text.ts [hunk 14]
```diff
@@ -1,35 +1,76 @@
...
+        if (tokens.length < blockSize + 1) {
+          // throw if it happens on the 1st chunk
+          if (chunkNumber === 0)
+            throw new Error(`the chunk (${tokens.length} tokens) is too small ` +
+              `to get a sequence of length blockSize (${blockSize + 1} tokens). ` +
+              `Either the text file or the chunk size is too small.`);
+          // if this isn't the first iteration we simply skip
+          // as we expect the last chunk to be potentially smaller than the block size
+          debug("chunk smaller than block size, loading next chunk")
+          return
```
Comment (tharvik) [inline discojs-web/src/loaders/text.ts]: isn't it the case where padding can be used instead? otherwise, we force a minimal text size (which is also hard to estimate, as various text length can generate the same number of token)

File: discojs-web/src/loaders/text.ts [hunk 15]
```diff
@@ -1,35 +1,76 @@
...
+        }
+        // keep the last tokens for the next chunk
+        // if this was the last chunk the remaining tokens are discarded
+        if (currentPosition < tokens.length) {
+          endOfPreviousChunk = tokenizer.decode(
+            tokens.slice(currentPosition),
+            { skip_special_tokens: true }
+          )
+        }
+        else endOfPreviousChunk = "";
```
Comment (tharvik) [inline discojs-web/src/loaders/text.ts]: using an index when it's a linear traversal is usually not needed and makes it harder to grasp.

```suggestion
        while (tokens.length >= blockSize + 1) {
          controller.enqueue(tokens.slice(0, blockSize + 1));
          tokens = tokens.slice(blockSize); // no +1 here
        }
        // keep the last tokens for the next chunk
        // if this was the last chunk the remaining tokens are discarded
        endOfPreviousChunk =
          tokens.length > 0
            ? tokenizer.decode(tokens, { skip_special_tokens: true })
            : "";
```

File: discojs-web/src/loaders/text.ts [hunk 16]
```diff
@@ -1,35 +1,76 @@
...
+        chunkNumber++;
       },
-      flush: (controller) => controller.enqueue(current_line),
+      // No flush, discard the last tokens
```
Comment (tharvik) [inline discojs-web/src/loaders/text.ts]: padding maybe? it's weird to have a loader of data not actually outputting all it can.

File: discojs/src/models/gpt/index.ts [hunk 17]
```diff
@@ -133,16 +135,31 @@ export class GPT extends Model {
...
+   * @param tokenizer tokenizer object
+   * @param generationConfig config object for text generation
+   * @param generationConfig.maxNewTokens default to 10, the number of tokens to generate
+   * @param generationConfig.temperature default to 1.0, the generation temperature (higher means more randomness). 
+   * Set to 0 for greedy decoding.
+   * @param generationConfig.doSample default to false, if true, sample the next token according the model's probabilities
+   * If false, predict the token with the highest probability.
+   * @param generationConfig.topk default to 50, only consider the topk most likely tokens for sampling. 
+   * Only used if doSample is true.
+   * @param generationConfig.seed default to 42, random seed for sampling.
```
Comment (tharvik) [inline discojs/src/models/gpt/index.ts]: better to push theses inside `GenerationConfig`: if we want at some point to publish the API (which I think we should if we want more devs to try out disco), it will be shown next to each field.

File: discojs/src/models/gpt/index.ts [hunk 18]
```diff
@@ -133,16 +135,31 @@ export class GPT extends Model {
...
+   * @returns the input prompt concatenated with the generated tokens
+   */
+  async generate(input: string, tokenizer: PreTrainedTokenizer, generationConfig?: Partial<GenerationConfig>): Promise<string> {
+    const { input_ids: tokens } = await tokenizer(input, {
+      return_tensor: false,
+      padding: false,
+    }) as { input_ids: number[] }
```
Comment (tharvik) [inline discojs/src/models/gpt/index.ts]: duplicated from `discojs/src/models/tokenizer.tokenize`

File: discojs/src/models/tokenizer.ts
Comment (tharvik) [inline discojs/src/models/tokenizer.ts:1]: yeah, I kind of dislike this file: it's exposing ~internal methods which isn't used outside of discojs-*.
* `getTaskTokenizer` is a quirk to correctly use `Task<"text">`
  * we can simplify this by having a serialization of `Task`, which would take care of materializing `Task.trainingInformation.tokenizer`, apply `Task`'s defaults, parse some fields as URL, …
* `tokenize` will probably not be needed anymore when rebased, as it would be in a processing method

File: discojs/src/models/gpt/layers.ts [hunk 19]
```diff
@@ -36,10 +42,17 @@ class LogLayer extends tf.layers.Layer {
...
-      }
+      if (Array.isArray(input)) input = input[0]
       this.invokeCallHook(input, kwargs)
+
+      const logs = {
+        // 'shape': input.shape,
+        // 'is_only_zero': !!input.equal(tf.tensor(0)).all().dataSync()[0],
+        // 'has_some_NaN': !!input.isNaN().any().dataSync()[0],
+        'min': +input.min().dataSync()[0].toPrecision(3),
+        'max': +input.max().dataSync()[0].toPrecision(3),
```
Comment (tharvik) [inline discojs/src/models/gpt/layers.ts:59]: is there a way to avoid `dataSync`? that hold the thread waiting for the data instead of allowing others to run

File: discojs/src/models/gpt/config.ts [hunk 20]
```diff
@@ -42,17 +40,15 @@ export const DEFAULT_CONFIG: Required<GPTConfig> = {
...
   debug: false,
   dropout: 0.2,
   residDrop: 0.2,
   embdDrop: 0.2,
-  tokEmb: true,
-  lmHead: true,
   nLayer: 3,
   nHead: 3,
   nEmbd: 48,
+  seed: 42,
```
Comment (tharvik) [inline discojs/src/models/gpt/config.ts]: that means that unless explicitly set, the model will always behave the same way, which might be unexpected. maybe we can `Math.random()` it if left undef before applying the default config?

File: discojs/src/models/gpt/layers.ts [hunk 21]
```diff
@@ -78,26 +95,35 @@ class CausalSelfAttention extends tf.layers.Layer {
...
-      'c_proj/kernel',
+      'c_proj.kernel',
       [this.nEmbd, this.nEmbd],
       'float32',
-      tf.initializers.glorotNormal({})
+      // the input keeps accumulating through the residual stream so we
+      // scale the initialization with the nb of layers to keep a unit std
+      // Sources:
+      // https://github.com/karpathy/build-nanogpt/blob/6104ab1b53920f6e2159749676073ff7d815c1fa/train_gpt2.py#L103
+      // https://youtu.be/l8pRSuU81PU?si=5GcKfi_kPgLgvtg2&t=4640
```
Comment (tharvik) [inline discojs/src/models/gpt/layers.ts:126]: nope to youtube tracking id

```suggestion
      // https://youtu.be/l8pRSuU81PU?t=4640
```

File: discojs/src/models/gpt/layers.ts [hunk 22]
```diff
@@ -121,77 +147,77 @@ class CausalSelfAttention extends tf.layers.Layer {
...
       }
       // Apply attention weights to inputs as one big matrix which is then split into the
       // query, key and value submatrices
+      // nHead is "number of heads", hs is "head size", and C (number of channels) = n_embd = nHead * hs
+      // e.g. in GPT-2 (124M), nHead = 12, hs = 64, so nHead * hs = C = 768 channels in the Transformer
       const cAttn = dense(input, this.cAttnKernel, this.cAttnBias)
-
       let [q, k, v] = tf.split(cAttn, 3, -1) as [tf.Tensor, tf.Tensor, tf.Tensor]
-      const [B, T, C] = k.shape
+      const [B, T, C] = k.shape // batch size, sequence length, embedding dimensionality (number of channels)
```
Comment (tharvik) [inline discojs/src/models/gpt/layers.ts:175]: instead of the comment, we can rename the variable? that helps when reading how it is used.
or at least, link the code/paper where theses names are used

File: discojs/src/models/gpt/layers.ts [hunk 23]
```diff
@@ -121,77 +147,77 @@ class CausalSelfAttention extends tf.layers.Layer {
...
+      y = dense(y, this.cProjKernel, this.cProjBias) // output projection (B, T, C)
+      y = kwargs.training === true ? tf.dropout(y, this.dropout, undefined, this.seed) : y
       return y
     })
   }
 }
 tf.serialization.registerClass(CausalSelfAttention)
 
+/**
+ * GELU with tanh approximate
```
Comment (tharvik) [inline discojs/src/models/gpt/layers.ts:226]: here my non-knowledge of ML shows: is see that many layers in TFJS can be activated using various function, such as 'gelu' or 'gelu_new'. as this layer is used once, between some dense layer, isn't it possible to merge some and drop this custom GELU implementation?

File: discojs/src/models/gpt/layers.ts [hunk 24]
```diff
@@ -210,81 +236,197 @@ class GELU extends tf.layers.Layer {
...
+      'wte', //use same name as GPT2
+      [this.vocabSize, this.nEmbd],
+      'float32',
+      tf.initializers.randomNormal({ mean:0, stddev:0.02, seed: this.seed })
+    )
+  }
+
+  override computeOutputShape(inputShape: tf.Shape | tf.Shape[]): tf.Shape | tf.Shape[] {
+    let shape: tf.Shape
+    if (Array.isArray(inputShape) && Array.isArray(inputShape[0])) shape = inputShape[0]
```
Comment (tharvik) [inline discojs/src/models/gpt/layers.ts]: it's only supporting a single `tf.Shape` there, consider throwing rather than silently dropping dimensions.

File: discojs/src/models/gpt/layers.ts [hunk 25]
```diff
@@ -210,81 +236,197 @@ class GELU extends tf.layers.Layer {
...
+      // https://github.com/tensorflow/tfjs/blob/3daf152cb794f4da58fce5e21e09e8a4f89c8f80/tfjs-layers/src/layers/embeddings.ts#L155
+      // batch size and sequence length are undetermined 
+      // so the output shape is [null, null, nEmbd]
+      return [...shape, this.nEmbd]
+    }
+    // input shape for the language modeling head
+    // https://github.com/tensorflow/tfjs/blob/3daf152cb794f4da58fce5e21e09e8a4f89c8f80/tfjs-layers/src/layers/core.ts#L258
+    else if (shape.length === 3) {
+      shape[2] = this.vocabSize
+      return shape // [null, null, vocabSize]
```
Comment (tharvik) [inline discojs/src/models/gpt/layers.ts]: this reads more easily. (maybe you can also check before that `shape[0..1]` are indeed `null`.

```suggestion
      return [null, null, this.vocabSize]
```

File: discojs/src/models/gpt/layers.ts [hunk 26]
```diff
@@ -210,81 +236,197 @@ class GELU extends tf.layers.Layer {
...
+  override computeOutputShape(inputShape: tf.Shape | tf.Shape[]): tf.Shape | tf.Shape[] {
+    let shape: tf.Shape
+    if (Array.isArray(inputShape) && Array.isArray(inputShape[0])) shape = inputShape[0]
+    else shape = inputShape as tf.Shape
+    // input shape for the token embedding
+    if (shape.length === 2) {
+      // https://github.com/tensorflow/tfjs/blob/3daf152cb794f4da58fce5e21e09e8a4f89c8f80/tfjs-layers/src/layers/embeddings.ts#L155
+      // batch size and sequence length are undetermined 
+      // so the output shape is [null, null, nEmbd]
+      return [...shape, this.nEmbd]
```
Comment (tharvik) [inline discojs/src/models/gpt/layers.ts]: better to simply return the values if we are sure of what it is.

```suggestion
      return [null, null, this.nEmbd]
```

File: discojs/src/models/gpt/layers.ts [hunk 27]
```diff
@@ -210,81 +236,197 @@ class GELU extends tf.layers.Layer {
...
+      shape[2] = this.vocabSize
+      return shape // [null, null, vocabSize]
+    }
+    else throw new Error('unexpected input shape')
+  }
+
+  override call (input: tf.Tensor | tf.Tensor[], kwargs: Record<string, unknown>): tf.Tensor | tf.Tensor[] {
+    return tf.tidy(() => {
+      if (this.embeddings === undefined) throw new Error('not built')
+      if (Array.isArray(input)) input = input[0]
```
Comment (tharvik) [inline discojs/src/models/gpt/layers.ts]: drops instead of the safer throw

File: discojs/src/models/gpt/layers.ts [hunk 28]
```diff
@@ -210,81 +236,197 @@ class GELU extends tf.layers.Layer {
...
+      // If the input is a 2D tensor, it is a batch of sequences of tokens
+      // so we translate the tokens into embeddings 
+      // using `this.embeddings` as a lookup table
+      if (input.shape.length === 2) {
+        // (batch_size, sequence_length) => (batch_size, sequence_length, nEmbd)
+        return tf.gather(this.embeddings.read(), tf.cast(input, 'int32'), 0)
+      }
+      // If the input is a 3D tensor, it is a sequence of embeddings
+      // so we apply a dense layer to project the embeddings back into the vocabulary space
+      else if (input.shape[2] === this.nEmbd) {
```
Comment (tharvik) [inline discojs/src/models/gpt/layers.ts]: more in sync with comment #nitpick (also consider using a switch, I find it sometimes more readable)

```suggestion
      else if (input.shape.length === 3) {
```

File: discojs/src/models/gpt/model.ts [hunk 29]
```diff
@@ -194,44 +177,70 @@ function prepareIdx (idx: tf.TensorLike): tf.Tensor2D {
...
-  async generate (idxRaw: tf.TensorLike, conf: GenerateConfig): Promise<number[][]> {
-    const config = Object.assign({}, defaultGenerateConfig, conf)
-    let idx = prepareIdx(idxRaw)
+
+  /**
+   * 
+   * @param input 
+   * @param config 
+   * @returns 
+   */
```
Comment (tharvik) [inline discojs/src/models/gpt/model.ts]: empty

```suggestion
```

File: discojs/src/models/gpt/model.ts [hunk 30]
```diff
@@ -194,44 +177,70 @@ function prepareIdx (idx: tf.TensorLike): tf.Tensor2D {
...
+        .slice([0, sequenceBatch.shape[1] - 1, 0]) // take the logits at the last position (B, 1, vocab_size)
+        .reshape([logits.shape[0], logits.shape[2]]) // (B, vocab_size)
+        .div<tf.Tensor2D>(tf.scalar(config.temperature)) // the higher the temperature, the more random the output
+      const probs = logitsScaled.softmax(-1) // get the token probabilities (B, vocab_size) 
       if (config.doSample) {
-        return tf.multinomial(probs, 1) as tf.Tensor2D
+        // returns topk biggest values among the `vocab_size` probabilities and the corresponding tokens indices 
+        // both shapes are (B, config.topk)
+        const { values: topkProbs, indices: topkTokens } = tf.topk(probs, config.topk);
+        // sample an index from the top-k probabilities
```
Comment (tharvik) [inline discojs/src/models/gpt/model.ts]: I don't quite understand why we filter the top-K values before sampling. is it to avoid unexpected (with a low probability) values? if yes, top-K would still allow unlikely values (if the distribution is very skewed toward a single token and not the others). maybe a threshold would be safer?

File: docs/CONTRIBUTING.md [hunk 31]
```diff
@@ -104,6 +104,69 @@ npm -w webapp test
 
 The webapp tests rely on `cypress` and the test suite is located in the `webapp/cypress` folder.
 
+Note that you can also run test interactively in the browser of your choice. To do so, run
+```
+cd webapp
+VITE_SERVER_URL=http://server npx start-server-and-test start http://localhost:8081 'cypress open --e2e'
```
Comment (tharvik) [inline docs/CONTRIBUTING.md]: you can use the same workspace argument as with `npm`

```suggestion
VITE_SERVER_URL=http://server npx -w webapp start-server-and-test start http://localhost:8081 'cypress open --e2e'
```

File: docs/CONTRIBUTING.md [hunk 32]
```diff
@@ -104,6 +104,69 @@ npm -w webapp test
...
+It is possible to record the cypress tests ran in the Github Actions CI and visualize them in the [Cypress Cloud](cloud.cypress.io). It is currently used only when needed (because the free plan has a limited number of recordings). The [cypress documentation](https://docs.cypress.io/app/continuous-integration/github-actions) describes how to set up the recordings.
+
+1. A Disco project has been created in the Cypress Cloud and you need to be added to the project to be able to visualize the recordings.
+
+2. In `webapp/cypress.config.ts` you need to add the project ID, which is currently:
+```js
+  projectId: "aps8et"
+```
+
+3. Finally, we can set the Cypress parameters in the Github Actions workflow `.github/workflows/lint-test-build.yml`, for example:
```
Comment (tharvik) [inline docs/CONTRIBUTING.md]: we can add a workflow especially for cypress, using a [`workflow_dispatch`](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_dispatch) event to only act when manually triggered

File: docs/CONTRIBUTING.md [hunk 33]
```diff
@@ -104,6 +104,69 @@ npm -w webapp test
...
+test-webapp:
+    needs: [build-lib, build-lib-web, download-datasets]
+    runs-on: ubuntu-latest
+    # Runs tests in parallel with matrix strategy https://docs.cypress.io/guides/guides/parallelization
+    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
+    # Also see warning here https://github.com/cypress-io/github-action#parallel
+    strategy:
+      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
+      matrix:
+        containers: [1, 2] # Uses 2 parallel instances
```
Comment (tharvik) [inline docs/CONTRIBUTING.md]: why parallelism is needed?

File: webapp/cypress.config.ts [hunk 34]
```diff
@@ -9,6 +9,10 @@ export default defineConfig({
       on("task", {
         readdir: async (p: string) =>
           (await fs.readdir(p)).map((filename) => path.join(p, filename)),
+        log: (message) => {
+          console.log(message)
+          return null
+        },
```
Comment (tharvik) [inline webapp/cypress.config.ts]: debug?

File: webapp/src/components/dataset_input/TextDatasetInput.vue [hunk 35]
```diff
@@ -10,20 +10,27 @@
...
-import type { Text } from "@epfml/discojs";
-import { Dataset } from "@epfml/discojs";
+import type { Text, Task } from "@epfml/discojs";
+import { Dataset, models } from "@epfml/discojs";
 import { loadText } from "@epfml/discojs-web";
 
 import DatasetInput from "./DatasetInput.vue";
 import FileSelection from "./FileSelection.vue";
 
+const { task } = defineProps<{ task: Task }>()
```
Comment (tharvik) [inline webapp/src/components/dataset_input/TextDatasetInput.vue]: [destructuring props only works in vue >= 3.5](https://vuejs.org/guide/components/props.html#reactive-props-destructure) but we are using vue 3.4 here

Comment (tharvik) [inline webapp/src/components/dataset_input/TextDatasetInput.vue]: I tried pretty hard to avoid referencing `Task` (the Ugly Global as I call it in my sleep), hopefully, it'll won't be needed with the latest changes to `loadText`

File: webapp/src/components/testing/TestSteps.vue [hunk 36]
```diff
@@ -39,12 +40,12 @@
         against a chosen dataset of yours. Below, once you assessed the model,
         you can compare the ground truth and the predicted values
         <div class="flex justify-center mt-4">
-          <CustomButton @click="startTest()"> test </CustomButton>
+          <CustomButton @click="startTest()" data-cy="start-test"> test </CustomButton>
```
Comment (tharvik) [inline webapp/src/components/testing/TestSteps.vue]: yeah, I saw that a few times in cypress' examples but I don't like this pattern. it mix test specific code into the rest of the codebase. especially here, it is possible to find a button with a "test" label.
same idea below.

**Review by tharvik — CHANGES_REQUESTED** [review]
superb work, thanks for clearing the GPT's mud, every comments makes it more understandable!
yeah, sadly, as I forgot to merge the processing PR (#781) before you branched off, the whole processing pipeline changed a lot. sorry for the toes stepping (hopefully, it will simplify this PR).

btw, it seems that @xenova/transformer [has been recently updated to @huggingface/transformer](https://github.com/huggingface/transformers.js/pull/545). did you try it out? maybe it'll help with the tokenizer usage (doesn't look much changed to me but you know best)

File: discojs-node/src/loaders/text.ts (hunk 3 above)
Comment (JulienVig) [reply discojs-node/src/loaders/text.ts]: Yes the one-token overlap is to make sure that that we predict the next token of each token in the block. And what we are currently doing is fairly predicting the next token of every single token in the batch (the mess going on in the attention layer actually performs the "slide over" the block via matrix operations)
This video bypasses the tokenization complexity by predicting at the character-level (i.e. the next letter rather than the next token). In any case, the video ends up by implementing the batches [similarly to us](https://github.com/karpathy/ng-video-lecture/blob/52201428ed7b46804849dea0b3ccf0de9df1a5c3/gpt.py#L41) by yielding batches with one-token overlap.
Similarly a more recent video/repository addresses the tokenization and also yields batches with overlap https://github.com/karpathy/build-nanogpt/blob/631f7d6f080effc4342b5e2f2f41879642c76fd1/train_gpt2.py#L184
Is it clearer or more confusing?

File: discojs/src/models/gpt/layers.ts (hunk 19 above)
Comment (JulienVig) [reply discojs/src/models/gpt/layers.ts:59]: I don't think so... At least this is only for debugging purposes.

File: discojs-node/src/loaders/text.ts (hunk 12 above)
Comment (JulienVig) [reply discojs-node/src/loaders/text.ts]: batchSize? not really it's another dimension of the model input, ideally we input a matrix [blockSize, batchSize] to the model so knowing both is useful to guess a good chunk size

File: discojs/src/models/gpt/model.ts (hunk 30 above)
Comment (JulienVig) [reply discojs/src/models/gpt/model.ts]: top k first filters out every value except the first k and then use softmax to get a probability distribution (so all the probability mass distributed over the tokens dropped is being reallocated on the first top k). I include top-k sampling because it's a very common strategy in language generation

File: discojs-node/src/loaders.spec.ts (hunk 7 above)
Comment (JulienVig) [reply discojs-node/src/loaders.spec.ts]: Okay I tried with some Llama tokenizers but the tokenization yields inconsistent tokens with the playgrounds I agree (which agree with each other).
I created an [issue upstream](https://github.com/huggingface/transformers.js/issues/1019) but not sure if they maintain the pretrained tokenizers

File: docs/CONTRIBUTING.md (hunk 32 above)
Comment (JulienVig) [reply docs/CONTRIBUTING.md]: Oh nice to good to know! But here we always want to run this test. I'm duplicating the test to have one always run without recording and one with recording when manually triggered.

File: discojs-node/src/loaders.spec.ts (hunk 5 above)
Comment (JulienVig) [reply discojs-node/src/loaders.spec.ts]: I'm not sure if you're asking for some changes or if you're saying it is good as it is?

File: discojs-node/src/loaders.spec.ts (hunk 8 above)
Comment (JulienVig) [reply discojs-node/src/loaders.spec.ts]: Ah the comment wasn't describing what was being tested but explaining why we shift by blocksize + 1, porr choice of words with "should have" I'm rephrasing the comment

File: discojs-node/src/loaders.spec.ts (hunk 10 above)
Comment (JulienVig) [reply discojs-node/src/loaders.spec.ts]: I moved out some things but I'm not sure that was all of what you were talking about

File: discojs-node/src/loaders.spec.ts (hunk 7 above)
Comment (JulienVig) [reply discojs-node/src/loaders.spec.ts]: I'm adding a test case with the Llama 3 tokenizer by comparing with the python tokenizer rather than using the playgrounds.

File: discojs-node/src/loaders.spec.ts (hunk 5 above)
Comment (tharvik) [reply discojs-node/src/loaders.spec.ts]: that's not super important but changing it to have a fixed list of token would be safer. so yeah, please do change it :)

File: discojs-node/src/loaders.spec.ts (hunk 10 above)
Comment (tharvik) [reply discojs-node/src/loaders.spec.ts]: yep, that was I wanted: the shortest the code inside `withFile`, the more readable it is for me, as it makes it clear when the file is not needed anymore.

File: discojs-node/src/loaders/text.ts (hunk 12 above)
Comment (tharvik) [reply discojs-node/src/loaders/text.ts]: ho yeah, totally right, I got my paintbrushes mixed there

**Comment by martinjaggi** [comment]
maybe rename block size to context len, that would be more specific

File: discojs-node/src/loaders/text.ts (hunk 1 above)
Comment (JulienVig) [reply discojs-node/src/loaders/text.ts]: Alright, the current implementation ended up being much simpler than my original tokenizing text loaders:
```js
loadText('../datasets/wikitext/wiki.train.tokens')
  .map(text => processing.tokenize(tokenizer, text)) // tokenize the whole chunk
  .flat() // (I renamed unbatch to flat)
  .batchWithOverlap(config.blockSize) // one token overlap between each batch
  .map((tokens) => [tokens.pop(), tokens.last()] as [List<number>, number])
  .batch(batchSize);
```

File: webapp/src/components/dataset_input/TextDatasetInput.vue (hunk 35 above)
Comment (JulienVig) [reply webapp/src/components/dataset_input/TextDatasetInput.vue]: Yay no need for the Task anymore

File: discojs-node/src/loaders/text.ts [hunk 37]
```diff
@@ -1,14 +1,34 @@
...
 
-export function load(path: string): Dataset<Text> {
+const debug = createDebug("discojs-node:loaders:text");
+
+/**
+ * Returns chunks of text. Use `minChunkSize` to ensure that 
+ * each chunk is bigger than the expected sequence length.
+ * 
+ * @param path path to the text file to read
+ * @param minChunkSize default to 16KiB, the minimum size of each chunk in bits
```
Comment (tharvik) [inline discojs-node/src/loaders/text.ts]: I don't see it being used anywhere in code, we can drop the parameter altogether

File: discojs/src/dataset/dataset.ts [hunk 38]
```diff
@@ -144,8 +144,48 @@ export class Dataset<T> implements AsyncIterable<T> {
...
+   * - The last batch is dropped as there are no next element to add.
+   *
+   * This method is tailored to create text sequences where each token's label is the following token. 
+   * In order to have a label for the last token of the input sequence, we include the first token
+   * of the next sequence.
+   * 
+   * @param size batch size excluding the overlapping element, at least 1
+   * @returns a dataset batch size `size + 1`
+   */
+  batchWithOverlap(size: number): Dataset<Batched<T>> {
```
Comment (tharvik) [inline discojs/src/dataset/dataset.ts]: I managed to get a slightly modified version of `batch` encompassing both use cases (except the "drop last batch if smaller than expected"). I don't feel as it burden `batch` much (and I find it a bit more readable than `batchWithOverlap`)

```diff
-  batch(size: number): Dataset<Batched<T>> {
+  batch(size: number, overlap = 0): Dataset<Batched<T>> {
     if (size <= 0 || !Number.isInteger(size)) throw new Error("invalid size");
+    if (overlap >= size || !Number.isInteger(overlap))
+      throw new Error("invalid overlap");

     return new Dataset(
       async function* (this: Dataset<T>) {
         const iter = this[Symbol.asyncIterator]();

+        let overlapped = List<T>();
         for (;;) {
           const batch = List(
-            await Promise.all(Range(0, size).map(() => iter.next())),
+            await Promise.all(
+              Range(overlapped.size, size).map(() => iter.next()),
+            ),
           ).flatMap((res) => {
             if (res.done) return [];
             else return [res.value];
@@ -135,50 +141,51 @@ export class Dataset<T> implements AsyncIterable<T> {

           if (batch.isEmpty()) break;

-          yield batch;
+          yield overlapped.concat(batch);
+          overlapped = batch.takeLast(overlap);

           // iterator couldn't generate more
-          if (batch.size < size) break;
+          if (batch.size < size - overlap) break;
         }
       }.bind(this),
     );
   }
```

File: discojs/src/dataset/dataset.ts [hunk 39]
```diff
@@ -176,6 +216,23 @@ export class Dataset<T> implements AsyncIterable<T> {
     );
   }
 
+  /**
+   * Repeat the dataset `times` times
+   * @param times number of times to repeat the dataset, if undefined, the dataset is repeated indefinitely
+   * @returns a dataset repeated `times` times
+   */
+  repeat(times?: number): Dataset<T> {
```
Comment (tharvik) [inline discojs/src/dataset/dataset.ts:208]: `repeat(0)` is the same as `repeat(1)`, I would be in favor of requiring that times > 0 (and integral).

File: discojs/src/dataset/dataset.ts [hunk 40]
```diff
@@ -176,6 +216,23 @@ export class Dataset<T> implements AsyncIterable<T> {
...
+    return new Dataset(
+      async function* (this: Dataset<T>) {
+        let loop = 0;
+        do {
+          for await (const e of this) yield e;
```
Comment (tharvik) [inline discojs/src/dataset/dataset.ts]: you can use the `yield*` meaning to yield everything from the given iterator.

```suggestion
          yield* this;
```

File: discojs/src/processing/text.ts [hunk 41]
```diff
@@ -1,47 +1,56 @@
...
+  config = { ...config }; // create a config if undefined
+  
+  if (config.padding || config.truncation) {
+    if (config.max_length === undefined) throw new Error("max_length needs to be specified to use padding or truncation");
+    if (!Number.isInteger(config.max_length))  throw new Error("max_length should be an integer");
+  }
+  
+  if (config.padding) {
+    // The padding side is set as an attribute, not in the config
+    tokenizer.padding_side = config.padding_side !== undefined ? config.padding_side : 'left'
```
Comment (tharvik) [inline discojs/src/processing/text.ts]:
```suggestion
    tokenizer.padding_side = config.padding_side ?? 'left'
```

File: discojs/src/processing/text.ts [hunk 42]
```diff
@@ -1,47 +1,56 @@
...
+import { List } from "immutable";
 import { PreTrainedTokenizer } from "@xenova/transformers";
+import type { Text, TokenizedText } from '../index.js'
 
 function isArrayOfNumber(raw: unknown): raw is number[] {
   return Array.isArray(raw) && raw.every((e) => typeof e === "number");
 }
 
-type Token = number;
+interface TokenizingConfig {
```
Comment (tharvik) [inline discojs/src/processing/text.ts:9]: can we have a smaller config? many of theses fields are arcane to me.

File: discojs/src/dataset/dataset.ts [hunk 43]
```diff
@@ -144,8 +144,48 @@ export class Dataset<T> implements AsyncIterable<T> {
...
+          // yield the current batch with the first element of the next batch
+          yield currentBatch.concat(nextFirstElement);
+          currentBatch = nextBatch
+        }
+      }.bind(this),
+    );
+  }
+
+  /** Flatten batches/arrays of elements */
+  flat<U>(this: Dataset<Batched<U>>): Dataset<U> {
```
Comment (tharvik) [inline discojs/src/dataset/dataset.ts]: `flatten` is a [more](https://immutable-js.com/docs/latest@main/List/#flatten()) [standard](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.flatten) name. also, now that we changed the name, we can input `DatasetLike<U>` instead of `Batched<U>` to allow flattening `List`, arrays, other `Dataset`, …

File: docs/CONTRIBUTING.md [hunk 44]
```diff
@@ -104,6 +104,60 @@ npm -w webapp test
...
+          wait-on: 'http://localhost:8081' # Waits for above
+          # Records to Cypress Cloud
+          # https://docs.cypress.io/guides/cloud/projects#Set-up-a-project-to-record
+          record: true
+        env:
+          VITE_SERVER_URL: http://server
+          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
+```
+
+Note that `CYPRESS_RECORD_KEY` is a repository secret which has already been added.
```
Comment (tharvik) [inline docs/CONTRIBUTING.md]: as it is now a dedicated workflow, we can reference it here instead of having a codeblock.

**Review by tharvik — APPROVED** [review]
only cosmetic comments, thanks for the huge amount of work :tada:

File: discojs/src/processing/text.ts (hunk 42 above)
Comment (JulienVig) [reply discojs/src/processing/text.ts:9]: I'm removing the non-essential ones but LLM generation is inherently complex (see the [HuggingFace docs](https://huggingface.co/docs/transformers/en/generation_strategies) for an overview of generation strategies)

File: discojs/src/dataset/dataset.ts (hunk 43 above)
Comment (JulienVig) [reply discojs/src/dataset/dataset.ts]: Because of code duplication with the constructor I created a common function to convert DatasetLike to AsyncGenerator, let me know if there was a simpler way to do it!

File: discojs/src/dataset/dataset.ts (hunk 38 above)
Comment (JulienVig) [reply discojs/src/dataset/dataset.ts]: Nice! Note that I had to change how we were calling batch with an overlap from `.batchSithOverlap(contextLength, 1)` to `.batch(contextLength + 1, 1)` as `batch` always returns batches of `size` elements.

**Comment by JulienVig** [comment]
I'll wait for #840 and #825 to be merged before this one.

File: discojs/src/dataset/dataset.ts (hunk 43 above)
Comment (tharvik) [reply discojs/src/dataset/dataset.ts]: ho, good idea, I was reusing the constructor but a standalone function is more readable :ok_hand:

**Comment by martinjaggi** [comment]
well done!
