### PR TITLE
Fix 404 error and wrong "upload" button

### LINKED ISSUE #680: Connecting folder displays alarming "Upload" warning message
The webapp allows connecting files in two different modes:
- connecting files by label, with one drag and drop zone for each task label
- connecting a csv linking filenames to labels and then all files at once:
Screenshot 2024-05-30 at 12 00 14

<br/><br/>
When using the 2nd option, the user is allowed to select the folder containing all the files (rather than selecting the files themselves). Selecting a folder currently poses two problems:
1. The selection menu displays an "Upload button" (at least on Mac OS) while we would prefer something like "Select" or "Connect" as there is no upload happening
Screenshot 2024-05-30 at 12 00 14
<br/><br/>
2. Selecting a folder with many files displays a warning message on Firefox and Chrome (not on Safari) asking the user to confirm whether they actually want to **upload** that many files.

Screenshot 2024-05-30 at 12 00 53
<br/><br/>
Screenshot 2024-05-30 at 11 59 22

### PR DESCRIPTION
**Pull request by JulienVig**
* Fixes #680 which was displaying wrong "upload" button when selecting folders.
* Fix 404 error happening when refreshing the website on a task page
* Add hover effect when drag and dropping
Screenshot 2024-07-24 at 18 40 42

The progress bars need a rework, they are not resilient and it is very hard to enforce consistency as they are many endpoints to modify their state

### CODE REVIEW

File: webapp/src/components/training/Training.vue [hunk 1]
```diff
@@ -38,22 +38,42 @@ import Finished from '@/components/training/Finished.vue'
...
+// Force the training store to synch with the task specified in the url
+watch(() => route.fullPath, () => {
+  if (route.fullPath !== '/list' && (trainingStore.step == 0 || route.params.id !== props.id)) {
+    setupTrainingStore()
   }
-  return task
 })
 
+onMounted(setupTrainingStore)
+
```
Comment (JulienVig) [inline webapp/src/components/training/Training.vue]: The tasksStore and trainingStore need a more time-consuming rework. I'm pushing this dirty implementation for the release until we have the time to address this.

File: webapp/src/components/data/dataset_input/DatasetInput.vue [hunk 2]
```diff
@@ -202,9 +207,9 @@ interface Props {
   datasetBuilder: data.DatasetBuilder<File>
   isOnlyPrediction: boolean //is true when predicting with a trained model
 }
-
 const props = defineProps<Props>()
 
+const browsingTip = "Tip: when browsing files you can use the keyboard shortcut Ctrl + A to select all images."
```
Comment (tharvik) [inline webapp/src/components/data/dataset_input/DatasetInput.vue:216]: let's inline it (only used once, is not changing)

File: webapp/src/components/data/dataset_input/FileSelection.vue [hunk 3]
```diff
@@ -145,30 +107,32 @@ interface Props {
   task: Task
   datasetBuilder: data.DatasetBuilder<File>
   csvRows: CSV,
-  isDirectory?: boolean, // is this input field accepts a directory
```
Comment (tharvik) [inline webapp/src/components/data/dataset_input/FileSelection.vue:148]: haa thank you, this "directory vs multiple" concept was always bothering me!

File: webapp/src/components/training/Training.vue [hunk 4]
```diff
@@ -38,22 +38,42 @@ import Finished from '@/components/training/Finished.vue'
 import Data from '@/components/data/Data.vue'
 
 const router = useRouter()
+const route = useRoute()
```
Comment (tharvik) [inline webapp/src/components/training/Training.vue:41]: same as above? I think you can merge both

File: webapp/src/components/training/Training.vue [hunk 5]
```diff
@@ -38,22 +38,42 @@ import Finished from '@/components/training/Finished.vue'
...
+  // This happens when refreshing the page, every task are reset when fetched
+  if (route.name !== 'task-list') {
+    router.replace({ name: 'task-list' })
+  }
+  return undefined
+})
+
+// Addresses the case when users enter a url manually
+// Force the training store to synch with the task specified in the url
+watch(() => route.fullPath, () => {
```
Comment (tharvik) [inline webapp/src/components/training/Training.vue:70]: hum, from a quick look at the doc, there seems to be [a nicer way to react to route changes](https://router.vuejs.org/guide/essentials/dynamic-matching.html#Reacting-to-Params-Changes)

File: webapp/src/components/training/Training.vue [hunk 6]
```diff
@@ -38,22 +38,42 @@ import Finished from '@/components/training/Finished.vue'
...
+  if (route.fullPath !== '/list' && (trainingStore.step == 0 || route.params.id !== props.id)) {
```
Comment (tharvik) [inline webapp/src/components/training/Training.vue]: full link look like too much information, and harder to keep track of (don't forget to update the watch target)

```suggestion
  if (route.name !== 'task-list' && (trainingStore.step == 0 || route.params.id !== props.id)) {
```

also, nitpicking on code style: I do like to have flatter functions' body, where `if` are there to "remove obstacles from the happy path". so, if most of the body of a function is wrapped inside an `if`, I would refactor it to rather return with the inverse condition. (arf, hard to explain, here goes some code)
```ts
function f() {
  if (cond) {
    …
  }
}
```
into
```ts
function f() {
  if (!cond) return
  …
}
```

so in our case here
```ts
() => {
  if (route.name === "task-list") return;
  if (trainingStore.step !== 0 && route.params.id === props.id) return;
  setupTrainingStore();
}
```
that reads a bit better IMO

File: webapp/src/components/training/Training.vue (hunk 1 above)
Comment (tharvik) [reply webapp/src/components/training/Training.vue]: yeah agree, we have to rework all the store usages, most of it isn't needed at all and can simply be replaced by correctly forwarding state from one step to the other.

File: webapp/src/store/tasks.ts [hunk 7]
```diff
@@ -16,8 +16,12 @@ export const useTasksStore = defineStore('tasks', () => {
   
   // used to display loading indicator in the webapp when loading tasks
   const loading = ref(false)
```
Comment (tharvik) [inline webapp/src/store/tasks.ts]: haa, my typing demons are coming back to haunt me!

consider using a more fun type, like `const loading = ref<'successed' | 'failed' | false>`.
no need to play with many variables, and it ensure state consistency.

**Review by tharvik — APPROVED** [review]
well done, that's way more stressful for users now! :closed_lock_with_key:
only some cosmetic comments as usual

File: webapp/src/components/data/dataset_input/DatasetInput.vue (hunk 2 above)
Comment (JulienVig) [reply webapp/src/components/data/dataset_input/DatasetInput.vue:216]: Good catch! it was supposed to be used twice! It got lost in some change reversion.

You were saying your limit is 3, mine is at 2 in this case. I believe that someone other than me would not necessarily notice it needs to be changed in 2 different places, especially if it's a quick change to reword or fix a typo.

File: webapp/src/components/training/Training.vue (hunk 4 above)
Comment (JulienVig) [reply webapp/src/components/training/Training.vue:41]: They are different objects!
From the [vue-router doc](https://router.vuejs.org/guide/): "The key thing to notice is that the composables useRouter() and useRoute() are used to access the router instance and current route respectively."

File: webapp/src/components/training/Training.vue (hunk 6 above)
Comment (JulienVig) [reply webapp/src/components/training/Training.vue]: I was actually using `route.name` but it's sometimes undefined, while `route.fullPath` is always defined. Which means I can be on the list page and route.name is sometimes 'task-list' and sometimes 'undefined' which is just calling for future issues.
I don't have a strong opinion on the function flatness, I'm in lining the method!

File: webapp/src/components/training/Training.vue (hunk 5 above)
Comment (JulienVig) [reply webapp/src/components/training/Training.vue:70]: Well, I just tried it and I can't get onBeforeRouteUpdate to trigger so I'll leave it as it is. There are also some technical differences between the two that I don't have time to test.

File: webapp/src/components/training/Training.vue (hunk 6 above)
Comment (JulienVig) [reply webapp/src/components/training/Training.vue:70]: Even seems that using route.fullPath triggers on mount and let's me remove the onMount hook

File: webapp/src/store/tasks.ts (hunk 7 above)
Comment (JulienVig) [reply webapp/src/store/tasks.ts]: Very neat! I don't like that  `if(loading) console.log(loading)` would print 'success' or 'failed'. This is unexpected since loading is true (it should be loading)
I'm changing it to `const status = ref<'success' | 'failed' | 'loading'>` to make everything explicit
